# Generated by Django 4.0.5 on 2022-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='artículo')),
                ('descripcion', models.TextField(verbose_name='Descripción del artículo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
    ]
